language: node_js
node_js:
  - "node"
  - "7"
  - "6"
before_script:
  - npm i -g gulp jshint && npm config set runtime travis -g
script: gulp && jshint ./dist/onebang.js --verbose && jshint ./dist/onebang.min.js --verbose